title = "Dataraft"
[application]
app_secret = "data-in-knowledge-out"
app_key = "dataraft"

[database]
username = ""
password = ""

[mongo]
host = "localhost"
port = 27017
username = "gagan"
password = "gaganuser"
database = "dataraft"